// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

#ifndef PROTOBUF_INCLUDED_message_2eproto
#define PROTOBUF_INCLUDED_message_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3007000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3007001 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_message_2eproto

// Internal implementation detail -- do not use these members.
struct TableStruct_message_2eproto {
  static const ::google::protobuf::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::google::protobuf::internal::ParseTable schema[1]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors_message_2eproto();
namespace com {
namespace limelight {
namespace protobuf {
class PositionInfo;
class PositionInfoDefaultTypeInternal;
extern PositionInfoDefaultTypeInternal _PositionInfo_default_instance_;
}  // namespace protobuf
}  // namespace limelight
}  // namespace com
namespace google {
namespace protobuf {
template<> ::com::limelight::protobuf::PositionInfo* Arena::CreateMaybeMessage<::com::limelight::protobuf::PositionInfo>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace com {
namespace limelight {
namespace protobuf {

// ===================================================================

class PositionInfo :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:com.limelight.protobuf.PositionInfo) */ {
 public:
  PositionInfo();
  virtual ~PositionInfo();

  PositionInfo(const PositionInfo& from);

  inline PositionInfo& operator=(const PositionInfo& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  PositionInfo(PositionInfo&& from) noexcept
    : PositionInfo() {
    *this = ::std::move(from);
  }

  inline PositionInfo& operator=(PositionInfo&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor() {
    return default_instance().GetDescriptor();
  }
  static const PositionInfo& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const PositionInfo* internal_default_instance() {
    return reinterpret_cast<const PositionInfo*>(
               &_PositionInfo_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(PositionInfo* other);
  friend void swap(PositionInfo& a, PositionInfo& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline PositionInfo* New() const final {
    return CreateMaybeMessage<PositionInfo>(nullptr);
  }

  PositionInfo* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<PositionInfo>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const PositionInfo& from);
  void MergeFrom(const PositionInfo& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  static const char* _InternalParse(const char* begin, const char* end, void* object, ::google::protobuf::internal::ParseContext* ctx);
  ::google::protobuf::internal::ParseFunc _ParseFunc() const final { return _InternalParse; }
  #else
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(PositionInfo* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // float posX = 1;
  void clear_posx();
  static const int kPosXFieldNumber = 1;
  float posx() const;
  void set_posx(float value);

  // float posY = 2;
  void clear_posy();
  static const int kPosYFieldNumber = 2;
  float posy() const;
  void set_posy(float value);

  // float posZ = 3;
  void clear_posz();
  static const int kPosZFieldNumber = 3;
  float posz() const;
  void set_posz(float value);

  // float rotX = 4;
  void clear_rotx();
  static const int kRotXFieldNumber = 4;
  float rotx() const;
  void set_rotx(float value);

  // float rotY = 5;
  void clear_roty();
  static const int kRotYFieldNumber = 5;
  float roty() const;
  void set_roty(float value);

  // float rotZ = 6;
  void clear_rotz();
  static const int kRotZFieldNumber = 6;
  float rotz() const;
  void set_rotz(float value);

  // float rotW = 7;
  void clear_rotw();
  static const int kRotWFieldNumber = 7;
  float rotw() const;
  void set_rotw(float value);

  // @@protoc_insertion_point(class_scope:com.limelight.protobuf.PositionInfo)
 private:
  class HasBitSetters;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  float posx_;
  float posy_;
  float posz_;
  float rotx_;
  float roty_;
  float rotz_;
  float rotw_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_message_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// PositionInfo

// float posX = 1;
inline void PositionInfo::clear_posx() {
  posx_ = 0;
}
inline float PositionInfo::posx() const {
  // @@protoc_insertion_point(field_get:com.limelight.protobuf.PositionInfo.posX)
  return posx_;
}
inline void PositionInfo::set_posx(float value) {
  
  posx_ = value;
  // @@protoc_insertion_point(field_set:com.limelight.protobuf.PositionInfo.posX)
}

// float posY = 2;
inline void PositionInfo::clear_posy() {
  posy_ = 0;
}
inline float PositionInfo::posy() const {
  // @@protoc_insertion_point(field_get:com.limelight.protobuf.PositionInfo.posY)
  return posy_;
}
inline void PositionInfo::set_posy(float value) {
  
  posy_ = value;
  // @@protoc_insertion_point(field_set:com.limelight.protobuf.PositionInfo.posY)
}

// float posZ = 3;
inline void PositionInfo::clear_posz() {
  posz_ = 0;
}
inline float PositionInfo::posz() const {
  // @@protoc_insertion_point(field_get:com.limelight.protobuf.PositionInfo.posZ)
  return posz_;
}
inline void PositionInfo::set_posz(float value) {
  
  posz_ = value;
  // @@protoc_insertion_point(field_set:com.limelight.protobuf.PositionInfo.posZ)
}

// float rotX = 4;
inline void PositionInfo::clear_rotx() {
  rotx_ = 0;
}
inline float PositionInfo::rotx() const {
  // @@protoc_insertion_point(field_get:com.limelight.protobuf.PositionInfo.rotX)
  return rotx_;
}
inline void PositionInfo::set_rotx(float value) {
  
  rotx_ = value;
  // @@protoc_insertion_point(field_set:com.limelight.protobuf.PositionInfo.rotX)
}

// float rotY = 5;
inline void PositionInfo::clear_roty() {
  roty_ = 0;
}
inline float PositionInfo::roty() const {
  // @@protoc_insertion_point(field_get:com.limelight.protobuf.PositionInfo.rotY)
  return roty_;
}
inline void PositionInfo::set_roty(float value) {
  
  roty_ = value;
  // @@protoc_insertion_point(field_set:com.limelight.protobuf.PositionInfo.rotY)
}

// float rotZ = 6;
inline void PositionInfo::clear_rotz() {
  rotz_ = 0;
}
inline float PositionInfo::rotz() const {
  // @@protoc_insertion_point(field_get:com.limelight.protobuf.PositionInfo.rotZ)
  return rotz_;
}
inline void PositionInfo::set_rotz(float value) {
  
  rotz_ = value;
  // @@protoc_insertion_point(field_set:com.limelight.protobuf.PositionInfo.rotZ)
}

// float rotW = 7;
inline void PositionInfo::clear_rotw() {
  rotw_ = 0;
}
inline float PositionInfo::rotw() const {
  // @@protoc_insertion_point(field_get:com.limelight.protobuf.PositionInfo.rotW)
  return rotw_;
}
inline void PositionInfo::set_rotw(float value) {
  
  rotw_ = value;
  // @@protoc_insertion_point(field_set:com.limelight.protobuf.PositionInfo.rotW)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace protobuf
}  // namespace limelight
}  // namespace com

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // PROTOBUF_INCLUDED_message_2eproto
